site_name: Research Software Good Practice
nav:
  - Home: index.md  
  - Webinar Series:
    - Good-practice:
      - 'Overview': 'good/overview.md'
      - 'Prerequisites': 'good/setup.md'
      - 'Monday': 'good/monday.md'    
      - 'Tuesday': 'good/tuesday.md'    
    - Vibe-coding:
      - 'Overview': 'vibe/overview.md'  
  - Admin:
    - 'Instructors':
      - 'Good-practice': 'good/instructor/overview.md'  
      
theme:
  name: material
  logo: assets/icr_svg_logo.svg  
  favicon: assets/icr_svg_logo.svg  
  palette:
    primary: pink  
    accent: deep orange  
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format